apiVersion: v1
kind: Secret
metadata:
  name: azure-services-secret
type: Opaque
stringData:
  # Azure OpenAI Configuration (Optional)
  azure-openai-endpoint: ""  # e.g., https://your-resource.openai.azure.com/
  azure-openai-api-key: ""
  azure-openai-deployment: ""  # e.g., gpt-35-turbo
  azure-openai-api-version: "2024-02-01"
  
  # Azure Document Intelligence Configuration (Optional)
  azure-docintel-endpoint: ""  # e.g., https://your-resource.cognitiveservices.azure.com/
  azure-docintel-api-key: ""
  azure-docintel-api-version: "2023-07-31"
  
  # Ollama Configuration (Optional)
  ollama-endpoint: ""  # e.g., http://your-ollama-server:11434
  ollama-model: "llama2"  # Default model name
  
  # OpenAI-compatible Configuration (Optional)
  openai-compatible-endpoint: ""  # e.g., https://api.openai.com or https://your-custom-endpoint
  openai-compatible-api-key: ""  # Optional for some endpoints
  openai-compatible-model: "gpt-3.5-turbo"  # Default model name