apiVersion: v1
kind: Pod
metadata:
  name: postgres-test-pod
  labels:
    app: postgres-test
spec:
  containers:
  - name: postgres-client
    image: postgres:15-alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    env:
    - name: PGHOST
      valueFrom:
        configMapKeyRef:
          name: postgres-config
          key: host
    - name: PGPORT
      valueFrom:
        configMapKeyRef:
          name: postgres-config
          key: port
    - name: PGDATABASE
      valueFrom:
        configMapKeyRef:
          name: postgres-config
          key: database
    - name: PGUSER
      valueFrom:
        configMapKeyRef:
          name: postgres-config
          key: username
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: password
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"