apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi  # Default Azure Disk CSI storage class
  resources:
    requests:
      storage: 1Gi